trigger:
- main  # Trigger the pipeline on changes to the main branch

pool:
  name: 'default'

jobs:
- job: Build
  displayName: 'Build Job'
  steps:

  # Checkout the code from the repository
  - checkout: self  # Automatically checks out the repository where this YAML file resides

  # Example step to use a .NET SDK (or any other environment you may need)
  - script: echo "Pipeline run complete"
    displayName: 'Echo Complete Message'
  # - script: exit 1
  #   displayName: 'Intentional Failure Step'
  # Publish the build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)'
      ArtifactName: 'simple-artifact'
      publishLocation: 'Container'
